language: c
before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_1.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :1 -ac -screen 0 1280x1024x16"
  - sleep 3
  - export DISPLAY=:1.0
  - wget http://downloads.arduino.cc/arduino-1.6.5-linux64.tar.xz
  - tar xf arduino-1.6.5-linux64.tar.xz
  - sudo mv arduino-1.6.5 /usr/local/share/arduino
  - sudo ln -s /usr/local/share/arduino/arduino /usr/local/bin/arduino
install:
  - sudo ln -s src/libraries/Adafruit_NeoPixel /usr/src/arduino/libraries/Adafruit_NeoPixel
  - sudo ln -s src/libraries/I2Cdev /usr/src/arduino/libraries/I2Cdev
  - sudo ln -s src/libraries/MPU6050 /usr/src/arduino/libraries/MPU6050
  - sudo ln -s src/libraries/SdFat /usr/src/arduino/libraries/SdFat
script:
  - arduino --verify --board arduino:avr:leonardo src/arduhoop/arduhoop.ino
